# Generated by Django 5.2.12 on 2026-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileactivitylog_fileaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='folder_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
